# Generated by Django 2.1.5 on 2019-02-17 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEmprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=250)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=500)),
                ('website', models.URLField(default='', max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to='starUp')),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=200)),
                ('place', models.TextField(default='', max_length=200)),
                ('begin_date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('start_hour', models.TimeField(default=datetime.time)),
                ('final_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_hour', models.TimeField(blank=True, default=datetime.time, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('organizer', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentarioemprendimiento',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eventos.Emprendimiento'),
        ),
    ]
