# Generated by Django 2.1.5 on 2019-02-12 22:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=200)),
                ('place', models.TextField(default='', max_length=200)),
                ('begin_date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('start_hour', models.TimeField(default=datetime.time)),
                ('final_date', models.DateField(default=datetime.date.today)),
                ('end_hour', models.TimeField(blank=True, default=datetime.time)),
                ('description', models.TextField(default='', max_length=500)),
                ('organizer', models.TextField(default='', max_length=50)),
                ('facebook', models.URLField(blank=True, default='', max_length=100)),
                ('instagram', models.URLField(blank=True, default='', max_length=100)),
                ('twitter', models.URLField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
