# Generated by Django 2.1.5 on 2019-01-30 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='evento',
            name='end_hour',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='evento',
            name='facebook',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='final_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='evento',
            name='instagram',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='organizer',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='start_hour',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='evento',
            name='twitter',
            field=models.URLField(default='', max_length=100),
        ),
    ]
