# Generated by Django 2.1.5 on 2019-02-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190219_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
