# Generated by Django 2.1.5 on 2019-02-12 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190212_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='end_hour',
            field=models.TimeField(blank=True, default=datetime.time, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='final_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
    ]
