# Generated by Django 2.1.5 on 2019-02-14 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190214_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioemprendimiento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
