# Generated by Django 2.1.5 on 2019-02-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190212_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
