# Generated by Django 2.1.5 on 2019-02-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20190219_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
