# Generated by Django 2.1.5 on 2019-02-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190214_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarioemprendimiento',
            old_name='comment_user',
            new_name='name',
        ),
    ]
