# Generated by Django 2.1.5 on 2019-02-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
