# Generated by Django 2.1.5 on 2019-02-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20190212_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='image',
        ),
    ]
