# Generated by Django 2.1.5 on 2019-02-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_evento_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
