# Generated by Django 2.1.5 on 2019-02-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
