# Generated by Django 2.1.5 on 2019-02-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20190213_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizer',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
    ]
