# Generated by Django 2.1.5 on 2019-02-13 20:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0008_auto_20190213_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioEmprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=250)),
                ('create_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=500)),
                ('website', models.URLField(default='', max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to='starUp')),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='user',
        ),
        migrations.AddField(
            model_name='evento',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioemprendimiento',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Emprendimiento'),
        ),
        migrations.AddField(
            model_name='comentarioemprendimiento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
