# Generated by Django 2.1.5 on 2019-02-14 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioemprendimiento',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentarioemprendimiento',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Emprendimiento'),
        ),
    ]
