# Generated by Django 2.1.5 on 2019-02-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20190213_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioemprendimiento',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emprendimiento', to='eventos.Emprendimiento'),
        ),
    ]
