# Generated by Django 2.1.5 on 2019-02-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20190214_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ComentarioEmprendimiento', to='eventos.ComentarioEmprendimiento'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='emprendimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ComentarioEmprendimiento', to='eventos.Emprendimiento'),
        ),
    ]
