# Generated by Django 2.1.5 on 2019-02-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20190213_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='username',
        ),
    ]
