# Generated by Django 2.1.5 on 2019-02-10 23:48

from django.db import migrations, models
import django.db.models.deletion
import uploadimages_rest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=uploadimages_rest.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
    ]
